### ISSUE TITLE
Update guzzle library to at least "^6.0"

### ISSUE THREAD

**Issue by danistor** [Judopay/Judo-PHP#35]
It is almost impossible to integrate in existing projects because most of the existing modern libraries require a minimum version of "guzzlehttp/guzzle" of "^6.0".

**Comment by aadilsheth** [comment]
Hi @danistor 

Thank you for your patience.

Please bear with us as we discuss this, we shall be back in touch with you soon.

Kind regards,

**Comment by chrisurun** [comment]
Hi @danistor 
We have decided to use Guzzle 5.x for our SDK to be compatible with PHP 5.4 (Guzzle ^6.0 does not support PHP 5.4). 
You can find more information on Guzzle versions and PHP support at https://github.com/guzzle/guzzle.

**Comment by j4k** [comment]
https://www.php.net/eol.php

Why are you supporting something that reached EOL 3 years, 8 months ago? Could you supply an official Guzzle 6 package for those of us that are running an up to date stack? We are having to maintain our own fork currently.

**Comment by chrisurun** [comment]
Hi @danistor @j4k 
We have updated our PHP SDK to use Guzzle 6
https://github.com/Judopay/Judo-PHP/releases/tag/4.0.0
