### ISSUE TITLE
Make a payment in PHP

### ISSUE THREAD

**Issue by jpaquete** [Judopay/Judo-PHP#40]
Cannot make a payment with php with exact code provided in the examples. Shows error:
Argument 1 passed to Judopay\\Helper\\ArrayHelper::get() must be of the type array, null given, called in /home/chargesurfing/vendor/judopay/judopay-sdk/src/Judopay/Exception/ApiException.php on line 46 and defined in /home/chargesurfing/vendor/judopay/judopay-sdk/src/Judopay/Helper/ArrayHelper.php:18\nStack trace:\n#0 /home/chargesurfing/vendor/judopay/judopay-sdk/src/Judopay/Exception/ApiException.php(46): Judopay\\Helper\\ArrayHelper::get(NULL, 'category', 0)\n#1 /home/chargesurfing/vendor/judopay/judopay-sdk/src/Judopay/Request.php(90): Judopay\\Exception\\ApiException::factory(Object(GuzzleHttp\\Exception\\ClientException))\n#2 /home/chargesurfing/vendor/judopay/judopay-sdk/src/Judopay/Model.php(125): Judopay\\Request->post('transactions/pa...', Array)\n#3 /home/ftp/ftpuser/chargesurfingwpsite/wp-content/themes/gtl-multipurpose-chargesurfing/chargesurfingapi_util.php(43): Judopay\\Model->create()\n#4 /home/ftp/ftpuser/chargesurfingwpsite/wp-content/themes/gtl-multipurpose-chargesurfing/chargesurfinga in /home/chargesurfing/vendor/judopay/judopay-sdk/src/Judopay/Helper/ArrayHelper.php on line 18

**Comment by freddy-onco** [comment]
Hi @jpaquete  , we are currently looking into this error, and we will relay back by email

**Comment by aftabafzaal** [comment]
I am having same issue right now

**Comment by aftabafzaal** [comment]
Catchable fatal error:  Argument 1 passed to Judopay\Helper\ArrayHelper::get() must be of the type array, null given, called in /Applications/XAMPP/xamppfiles/htdocs/judopay/vendor/judopay/judopay-sdk/src/Judopay/Exception/ApiException.php on line 47 and defined in /Applications/XAMPP/xamppfiles/htdocs/judopay/vendor/judopay/judopay-sdk/src/Judopay/Helper/ArrayHelper.php on line 18

**Comment by jpaquete** [comment]
aftabafzaal. Still no concrete resolution for this problem. I suspect the main branch is broken. I was told by dev team member that this situation was not reproducible on their side... Glad someone has the same issue. May be this time it will get fixed ;)

**Comment by zggonzalez** [comment]
Do you guys have any feedback on this? When is this going to be fixed? Thx in advance. I fixed by setting up the Client request like this:

$client = new Client([
                    **'base_uri' => $configuration->get("endpointUrl"),**
                    'verify' =>  SGL_LIB_DIR . '/vendor/judopay/judopay-sdk/cert/digicert_sha256_ca.pem'
                ]);

in this file: https://github.com/Judopay/Judo-PHP/blob/master/src/Judopay.php

**Comment by freddy-onco** [comment]
@zggonzalez  Thank you , can you please submit this change for PR , so our Dev team can review it ?

Many Thanks

**Comment by hamza-mostafa** [comment]
@freddy-onco Thanks for the follow up and support, I have made a PR. kind regards,
 Hamza

**Comment by zggonzalez** [comment]
Thx guys.

**Comment by freddy-onco** [comment]
Thank you @hamza-mostafa   ,  @zggonzalez  PR approved and merged

**Comment by zggonzalez** [comment]
It would be great to have 3DS2 implemented in this library. Do you have any timeline for this? Thx in advance.

**Comment by chrisurun** [comment]
Issue resolved thanks to this PR: https://github.com/Judopay/Judo-PHP/pull/41
